### ISSUE TITLE
Remove implicit dependency on outdated guzzle/guzzle

### ISSUE THREAD

**Issue by stucki** [seboettg/Collection#1]
This project depends on `"satooshi/php-coveralls": "^1"` which loads `guzzle/guzzle`. This project is abandoned and results in a warning when running `composer update`:
`Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.`

Unfortunately, the developers at https://github.com/satooshi/php-coveralls/ seem unwilling to add a simple fix for this problem, see https://github.com/satooshi/php-coveralls/issues/203.

I propose two solutions to fix the issue, choose what you prefer more:
- move the dependency to `require-dev` (because it's only needed for that)
- alternatively, change the dependency to `"satooshi/php-coveralls": "dev-master"`

Let me know if I should create a pull request for this.

**Comment by seboettg** [comment]
Hi, thank you for this issue. Feel free to create PR for this.
Thanks!

**Comment by stucki** [comment]
Which of the two approaches do you prefer?
