### ISSUE TITLE
Use splat operator for constructor

### ISSUE THREAD

**Issue by tdtm** [seboettg/Collection#3]
So we can use it with a variable number or arguments
```
$arrayList = new ArrayList($el, $el2, $el3);
```
or an array
```
$array = [$el, $el2, $el3];
$arrayList = new ArrayList(...$array);
```

The biggest motivation to do this is then being able to extend this with another class and type it to then add some more type-specific functionality:

```
    abstract class AbstractEntity extends \stdClass {...}

    /**
     * @property AbstractEntity[] $array
     */
    class EntityList extends ArrayList
    {
        public function __construct(AbstractEntity ...$data) { parent::__construct(...$data); }
    }
```

I've forked it and pretty much done it already. I'll need to complete tests and do a PR soon.

**Comment by seboettg** [comment]
solved with v2.0.0
